

# POST http://localhost:10000/user HTTP/1.1
# content-type: application/json

# {
#     "Id":"3",
#     "Name":"new user",
#     "Username":"new username",
#     "Email":"example@user.com"
# }



# GET http://localhost:10000/users